export const projects = [
    {
        preview_image:"",
        preview_heading:"Job Finder",
        preview_description:"ICK training program project",

        modal:{
            first_image:"",
            second_image:"",
            right_content:[
                {
                    title:"",
                    description:""
                },
                {
                    title:"",
                    description:""
                },
                {
                    title:"",
                    description:""
                },
            ],
            left_content:[
                {
                    title:"",
                    description:""
                }
            ]
        }
    },
    {
        preview_image:"",
        preview_heading:"",
        preview_description:"",

        modal:{
            first_image:"",
            second_image:"",
            right_content:[
                {
                    title:"",
                    description:""
                },
                {
                    title:"",
                    description:""
                },
                {
                    title:"",
                    description:""
                },
            ],
            left_content:[
                {
                    title:"",
                    description:""
                }
            ]
        }
    },
    {
        preview_image:"",
        preview_heading:"",
        preview_description:"",

        modal:{
            first_image:"",
            second_image:"",
            right_content:[
                {
                    title:"",
                    description:""
                },
                {
                    title:"",
                    description:""
                },
                {
                    title:"",
                    description:""
                },
            ],
            left_content:[
                {
                    title:"",
                    description:""
                }
            ]
        }
    },
    {
        preview_image:"",
        preview_heading:"",
        preview_description:"",

        modal:{
            first_image:"",
            second_image:"",
            right_content:[
                {
                    title:"",
                    description:""
                },
                {
                    title:"",
                    description:""
                },
                {
                    title:"",
                    description:""
                },
            ],
            left_content:[
                {
                    title:"",
                    description:""
                }
            ]
        }
    }
]